"use client";
import './console-theme.css';
import { useState, useEffect, FormEvent } from 'react';
import { Shield, Layers, SlidersHorizontal, Power, History, GitPullRequest, Plus, RefreshCw, ArrowUpRight, LogOut, CheckCircle2 } from 'lucide-react';
import { request, Row, baseUrl } from '@/lib/api';
import RunHistory from './run-history';
import { Globe, MetricCards, StatusCard, RightRail } from './console-visuals';
const sections = [
  {name:'Workflows',path:'workflows',icon:Layers,description:'Registered operations and their risk classifications.'},
  {name:'Policies',path:'control-policies',icon:SlidersHorizontal,description:'Explicit permissions and restrictions for model execution.'},
  {name:'Emergency stops',path:'kill-switches',icon:Power,description:'Stop new model calls globally or for a specific workflow.'},
  {name:'Change requests',path:'change-requests',icon:GitPullRequest,description:'Prepare changes and track independent review and approval.'},
  {name:'Audit trail',path:'audit-events',icon:History,description:'Persisted governance decisions and operator activity.'},
  {name:'Orchestration runs',path:'orchestrations/runs',icon:History,description:'See each agent step, its outcome, and the controls that governed it.'}
];
async function readHealth():Promise<{status:string;latency:number|null}>{const start=performance.now();try{const response=await fetch(baseUrl+'/health');const data=await response.json();return {status:response.ok?data.status:'unavailable',latency:Math.round(performance.now()-start)};}catch{return {status:'unavailable',latency:null};}}
export default function Home() {
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all');
  const [runs,setRuns]=useState<Row[]>([]); const [loaded,setLoaded]=useState(false);
  const [health,setHealth]=useState('checking'); const [latency,setLatency]=useState<number|null>(null);
  const [ssoEnabled,setSsoEnabled]=useState(false);
  const [token,setToken]=useState(''); const [draftKey,setDraftKey]=useState('');
  const [actor,setActor]=useState<{name:string;role:string}|null>(null);
  const [section,setSection]=useState(0); const [rows,setRows]=useState<Row[]>([]);
  const [workflows,setWorkflows]=useState<Row[]>([]); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [busy,setBusy]=useState(false); const [form,setForm]=useState(false); const [selected,setSelected]=useState<Row|null>(null);
  const current=sections[section];
  const visibleRows=rows.filter(row=>(filter==='all'||(filter==='active'?row.is_active:!row.is_active))&&`${row.name||row.title||row.event_type||''} ${row.id}`.toLowerCase().includes(query.toLowerCase()));
  async function checkHealth(){const result=await readHealth();setHealth(result.status);setLatency(result.latency);}
  async function load(index=section, key=token) {setBusy(true);setError('');void checkHealth();try {const [data,registry,history]=await Promise.all([request<Row[]>(sections[index].path,key),request<Row[]>('workflows',key),request<Row[]>('orchestrations/runs',key)]);setRows(data);setWorkflows(registry);setRuns(history);setLoaded(true);}catch(e){setError((e as Error).message);setRows([]);setLoaded(false);}finally{setBusy(false);}}
  function navigate(index:number){setSection(index);setSelected(null);setForm(false);setNotice('');setQuery('');setFilter('all');void load(index);}
  // Bootstrap the existing cookie session once; navigation refreshes data explicitly.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void request<{enabled:boolean}>('auth/config','').then(c=>setSsoEnabled(c.enabled)).catch(()=>{});void request<{name:string;role:string}>('me','').then(identity=>{setActor(identity);void load(0,'');}).catch(()=>{});},[]);
  async function login(e:FormEvent) {e.preventDefault();setBusy(true);setError('');try {const identity=await request<{name:string;role:string}>('me',draftKey);setActor(identity);setToken(draftKey);setDraftKey('');await load(0,draftKey);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function mutate(path:string,body?:unknown,method='POST') {setBusy(true);setError('');setNotice('');try{await request(path,token,method,body);setForm(false);setSelected(null);setNotice('Saved to the control plane.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function create(e:FormEvent<HTMLFormElement>) {e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));let payload:Record<string,unknown>=data;
    if(section===1) payload={...data, workflow_id:data.workflow_id || null, conditions:data.model ? {model:data.model}: {}};
    if(section===1) delete payload.model;
    if(section===2) payload={...data,workflow_id:data.workflow_id || null};
    if(section===3) payload={...data,workflow_id:data.workflow_id || null,rollback_procedure:{instructions:data.rollback}};
    if(section===3) delete payload.rollback;
    await mutate(current.path,payload);
  }
  if(!actor) return <main className="login"><div className="login-brand"><Shield size={32}/><span>R.A.E.</span></div><form onSubmit={login} className="login-card"><p className="eyebrow">RUNTIME AUTHORITY ENGINE</p><h1>Enter the control plane.</h1><p>Connect with your operator API key to manage workflows and governance controls.</p>{ssoEnabled&&<a className="primary" href={baseUrl+"/api/auth/login"}>Sign in with Southern Shade SSO</a>}<label>API key<input type="password" autoComplete="off" value={draftKey} onChange={e=>setDraftKey(e.target.value)} required placeholder="Your installation’s API key"/></label><button disabled={busy} className="primary">{busy?'Connecting…':'Connect'}<ArrowUpRight size={18}/></button>{error&&<p role="alert" className="error">{error}</p>}<p className="small">Keys stay in memory and are cleared when you disconnect or reload.</p></form><p className="login-foot">SOUTHERN SHADE TECHNOLOGIES / LOCAL OPERATOR CONSOLE</p></main>;
  return <div className="shell"><aside><div className="brand"><Shield size={26}/><strong>R.A.E.</strong><span>RUNTIME<br/>AUTHORITY<br/>ENGINE</span></div><p className="nav-label">CONTROL PLANE</p><div className="workspace"><span className="eyebrow">WORKSPACE</span><strong>Southern Shade Technologies</strong><span>Runtime governance</span></div><nav aria-label="Main navigation">{sections.map((s,i)=><button key={s.path} className={section===i?'active':''} onClick={()=>navigate(i)} disabled={busy}><s.icon size={19}/>{s.name}</button>)}</nav><div className="sidebar-bottom"><span className="avatar">{actor.name.slice(0,2).toUpperCase()}</span><div><strong>{actor.name}</strong><span>{actor.role}</span></div><button aria-label="Disconnect" onClick={async()=>{if(!token){try{await request("auth/logout","","POST");}catch(e){setError((e as Error).message);return;}}setActor(null);setToken('');setRows([]);setSection(0);}}><LogOut size={17}/></button></div></aside><main className="main"><header className="topbar"><span>Control plane <span className="slash">/</span> {current.name}</span><div className="topbar-tools"><label className="global-search"><span>⌕</span><input aria-label="Search current section" placeholder="Search this section…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="environment">LOCAL</span><span className="avatar">{actor.name.slice(0,2).toUpperCase()}</span></div></header><div className="content"><div className="hero"><Globe/><div className="page-heading"><div><p className="eyebrow">RUNTIME AUTHORITY ENGINE</p><h1>{current.name}</h1><h2 className="hero-tagline">Orchestrate. Govern. Execute.</h2><p>{current.description}</p><blockquote>“Control today.<br/>Safer tomorrow.”</blockquote></div><div className="actions"><button onClick={()=>void load()} disabled={busy} aria-label="Refresh"><RefreshCw size={17}/></button>{section<4&&actor.role!=='viewer'&&<button className="primary" disabled={busy || ((section===1||section===2)&&actor.role!=='admin')} onClick={()=>{setForm(true);setSelected(null);}}><Plus size={17}/>New {section===0?'workflow':section===1?'policy':section===2?'stop':'request'}</button>}{section===4&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await request<{valid:boolean;verified_count:number}>('audit-events/verify',token);setNotice(result.valid?`Verified ${result.verified_count} events. Chain is intact.`:'Audit chain verification failed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Verify chain</button>}</div></div><StatusCard health={health} latency={latency}/></div><div className="dashboard-columns"><div className="primary-column"><MetricCards workflows={workflows} loaded={loaded}/>{error&&<div role="alert" className="error banner">{error}</div>}{notice&&<div role="status" className="notice banner"><CheckCircle2 size={17}/>{notice}</div>}
      {form&&<section className="panel form-panel"><div className="panel-title"><h2>Create {current.name.toLowerCase().replace(/s$/,'')}</h2><button onClick={()=>setForm(false)}>Cancel</button></div><form onSubmit={create} className="edit-form"><label>{section===3?'Title':'Name'}<input name={section===3?'title':'name'} required maxLength={255}/></label>{section!==2&&<label>Description<input name="description" required={section===3}/></label>}{section===0&&<><label>Version<input name="version" defaultValue="1.0.0" required/></label><label>Risk level<select name="risk_level"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label></>}{section>0&&<label>Workflow scope<select name="workflow_id"><option value="">All workflows</option>{workflows.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label>}{section===1&&<><label>Action<select name="policy_action"><option value="deny">Deny</option><option value="allow">Allow</option><option value="require_approval">Require review (blocks execution)</option></select></label><label>Model match<input name="model" placeholder="Leave empty to match all models"/></label></>}{section===2&&<label>Reason<input name="reason" required/></label>}{section===3&&<><label>Rationale<input name="rationale" required/></label><label>Rollback procedure<textarea name="rollback" required/></label><label>Risk level<select name="risk_level"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label></>}<div className="form-footer"><button disabled={busy} className="primary">{busy?'Saving…':'Create'}</button></div></form></section>}
      {section!==5&&<><section className="panel"><div className="table-toolbar"><label className="table-search"><input aria-label="Filter records" placeholder={`Search ${current.name.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/></label>{section<3&&<div className="filter-pills">{["all","active","inactive"].map(value=><button key={value} className={filter===value?"selected":""} onClick={()=>setFilter(value)}>{value}</button>)}</div>}</div><div className="panel-title"><h2>{current.name}</h2><span>{busy?'Loading…':`${rows.length} records · latest 100`}</span></div>{!busy&&!visibleRows.length?<div className="empty"><current.icon size={32}/><h3>No {current.name.toLowerCase()} yet</h3><p>{section===4?'Governance activity will appear here as you use the console.':'Create your first record to begin.'}</p></div>:<div className="table-wrap"><table><thead><tr><th>{section===4?'Event':'Name'}</th><th>{section===4?'Outcome':'Status'}</th><th>{section===0?'Risk / version':section===1?'Action':section===2?'Scope':'Created'}</th><th>Details</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id}><td><strong>{row.name||row.title||row.event_type}</strong><span className="row-sub">{section===4?`Sequence ${row.sequence_number}`:row.description||row.id.slice(0,8)}</span></td><td><span className={`badge ${(row.outcome==='BLOCKED'||row.is_active&&section===2)?'warning':section<3&&!row.is_active?'inactive':''}`}>{section<3?(row.is_active?'Active':'Inactive'):(row.status||row.outcome||'—')}</span></td><td>{section===0?`${row.risk_level} / ${row.version}`:section===1?row.policy_action:section===2?(row.workflow_id?'Workflow':'Global'):row.created_at?new Date(row.created_at+'Z').toLocaleString():'—'}</td><td><button onClick={()=>{setSelected(row);setForm(false);}}>View</button></td></tr>)}</tbody></table></div>}</section></>}
      {selected&&<section className="panel detail"><div className="panel-title"><h2>{selected.name||selected.title||selected.event_type}</h2><button onClick={()=>setSelected(null)}>Close</button></div>{section===2&&actor.role==='admin'&&<form onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');void mutate(`kill-switches/${selected.id}/${selected.is_active?'deactivate':'activate'}`,{reason});}} className="edit-form"><label>{selected.is_active?'Resolution notes':'Activation reason'}<input name="reason" required/></label><button disabled={busy} className={selected.is_active?'primary':'danger'}>{selected.is_active?'Release stop':'Activate emergency stop'}</button></form>}{section===3&&actor.role!=='viewer'&&<div className="edit-form">{selected.status==='DRAFT'?<button disabled={busy} onClick={()=>void mutate(`change-requests/${selected.id}/submit`)}>Submit for review</button>:actor.role==='admin'&&(selected.status==='UNDER_REVIEW'||selected.status==='PENDING_APPROVAL')?<form onSubmit={e=>{e.preventDefault();void mutate(`change-requests/${selected.id}/${selected.status==='UNDER_REVIEW'?'review':'approve'}`,{notes:new FormData(e.currentTarget).get('notes')});}}><label>Decision notes<input name="notes" required/></label><button disabled={busy}>Record {selected.status==='UNDER_REVIEW'?'review':'approval'}</button></form>:null}</div>}{(section===0||section===1)&&selected.is_active&&actor.role==='admin'&&<div className="edit-form"><button disabled={busy} onClick={()=>void mutate(`${current.path}/${selected.id}`,undefined,'DELETE')}>Deactivate {section===0?'workflow':'policy'}</button></div>}<pre>{JSON.stringify(selected,null,2)}</pre></section>}
      {section===5&&<RunHistory rows={visibleRows} workflows={workflows} token={token} canSubmit={actor.role!=='viewer'}/>}
      </div><RightRail workflows={workflows} runs={runs} loaded={loaded} onRuns={()=>navigate(5)}/></div><footer>R.A.E. v0.2 <span>Authenticated operations · Persistent audit history</span></footer></div></main></div>;
}
