"""Initial schema

Revision ID: bdc5931c12bf
Revises: 
Create Date: 2026-06-13 22:40:24.185390+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdc5931c12bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("actor_type IN ('USER', 'AGENT', 'SYSTEM', 'API_KEY', 'SERVICE_ACCOUNT')", name='valid_actor_type'),
    sa.CheckConstraint("outcome IN ('SUCCESS', 'FAILURE', 'BLOCKED', 'WARNING', 'ERROR')", name='valid_outcome'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash'),
    sa.UniqueConstraint('sequence_number'),
    comment='Immutable audit log with cryptographic hash chaining (Phase 3: Enforcement)'
    )
    op.create_index('idx_audit_actor_time', 'audit_events', ['actor_id', 'created_at'], unique=False)
    op.create_index('idx_audit_event_type_time', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_audit_outcome', 'audit_events', ['outcome', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_events', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_tenant_key'), 'tenants', ['tenant_key'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_key', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DEACTIVATED', name='workflowstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_workflow_name_version')
    )
    op.create_index(op.f('ix_workflows_workflow_key'), 'workflows', ['workflow_key'], unique=True)
    op.create_table('break_glass',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('break_glass_key', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('P0_INCIDENT', 'DATA_LOSS', 'SECURITY_RESPONSE', 'REGULATORY', 'CUSTOMER_IMPACT', 'SYSTEM_FAILURE', name='breakglassreason'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', 'REVOKED', name='breakglassstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('denied_by', sa.String(length=255), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('post_incident_review_completed', sa.Boolean(), nullable=False),
    sa.Column('post_incident_notes', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_glass_break_glass_key'), 'break_glass', ['break_glass_key'], unique=True)
    op.create_index(op.f('ix_break_glass_incident_id'), 'break_glass', ['incident_id'], unique=False)
    op.create_index(op.f('ix_break_glass_workflow_id'), 'break_glass', ['workflow_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_key', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_capability_key'), 'capabilities', ['capability_key'], unique=True)
    op.create_index(op.f('ix_capabilities_workflow_id'), 'capabilities', ['workflow_id'], unique=False)
    op.create_table('control_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_action', sa.Enum('ALLOW', 'DENY', 'REQUIRE_APPROVAL', 'DEGRADE', name='policyaction'), nullable=False),
    sa.Column('approval_type', sa.Enum('NONE', 'SINGLE', 'DUAL', 'COMMITTEE', name='approvaltype'), nullable=False),
    sa.Column('approval_required_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approver_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_deny_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('last_modified_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_policies_policy_key'), 'control_policies', ['policy_key'], unique=True)
    op.create_index(op.f('ix_control_policies_workflow_id'), 'control_policies', ['workflow_id'], unique=False)
    op.create_table('kill_switches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('switch_key', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.Enum('HARD_STOP', 'SOFT_STOP', 'READ_ONLY', 'DEGRADE', name='killswitchmode'), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'INCIDENT', 'SECURITY', 'COMPLIANCE', 'AUTOMATED', 'DATA_ANOMALY', name='killswitchtrigger'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('auto_deactivate_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(length=255), nullable=True),
    sa.Column('deactivated_by', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switches_incident_id'), 'kill_switches', ['incident_id'], unique=False)
    op.create_index(op.f('ix_kill_switches_switch_key'), 'kill_switches', ['switch_key'], unique=True)
    op.create_index(op.f('ix_kill_switches_workflow_id'), 'kill_switches', ['workflow_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_key', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.Enum('WORKFLOW_DEPLOYMENT', 'WORKFLOW_MODIFICATION', 'CAPABILITY_GRANT', 'CAPABILITY_REVOKE', 'CONTROL_POLICY_UPDATE', 'EMERGENCY_ACCESS', 'MODEL_DEPLOYMENT', 'CONFIG_CHANGE', name='changetype'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='changerisklevel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('capability_id', sa.UUID(), nullable=True),
    sa.Column('control_policy_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'PENDING_APPROVAL', 'APPROVED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ROLLED_BACK', 'REJECTED', 'CANCELLED', name='changestatus'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('approver_email', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('change_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('testing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('verification_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_completed', sa.Boolean(), nullable=False),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('verification_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_procedure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_executed', sa.Boolean(), nullable=False),
    sa.Column('rollback_executed_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_successful', sa.Boolean(), nullable=True),
    sa.Column('audit_event_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_policy_id'], ['control_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Governed change requests for high-risk production changes (Phase 3: Enforcement - FLAGSHIP)'
    )
    op.create_index('idx_change_execution_window', 'change_requests', ['scheduled_start', 'scheduled_end'], unique=False)
    op.create_index('idx_change_requested', 'change_requests', ['requested_by', 'requested_at'], unique=False)
    op.create_index('idx_change_status_risk', 'change_requests', ['status', 'risk_level'], unique=False)
    op.create_index('idx_change_workflow', 'change_requests', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_change_requests_capability_id'), 'change_requests', ['capability_id'], unique=False)
    op.create_index(op.f('ix_change_requests_change_key'), 'change_requests', ['change_key'], unique=True)
    op.create_index(op.f('ix_change_requests_change_type'), 'change_requests', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_requests_control_policy_id'), 'change_requests', ['control_policy_id'], unique=False)
    op.create_index(op.f('ix_change_requests_requested_by'), 'change_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_change_requests_risk_level'), 'change_requests', ['risk_level'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_change_requests_workflow_id'), 'change_requests', ['workflow_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_key', sa.String(length=255), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_type', sa.Enum('API', 'DATABASE', 'MESSAGE_QUEUE', 'S3_BUCKET', 'ML_MODEL', 'LAMBDA', 'EXTERNAL_SERVICE', name='connectortype'), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_capability_id'), 'connectors', ['capability_id'], unique=False)
    op.create_index(op.f('ix_connectors_connector_key'), 'connectors', ['connector_key'], unique=True)
    op.create_table('enforcement_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_key', sa.String(length=100), nullable=False),
    sa.Column('gate_type', sa.Enum('PRE_EXECUTION', 'POST_EXECUTION', 'CAPABILITY_REQUEST', 'PRODUCTION_CHANGE', 'DATA_ACCESS', 'MODEL_DEPLOYMENT', 'BREAK_GLASS_ENTRY', name='gatetype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('capability_id', sa.UUID(), nullable=True),
    sa.Column('control_policy_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('enforcement_mode', sa.String(length=50), nullable=False),
    sa.Column('require_all_pass', sa.Boolean(), nullable=False),
    sa.Column('check_kill_switches', sa.Boolean(), nullable=False),
    sa.Column('capture_inputs', sa.Boolean(), nullable=False),
    sa.Column('capture_outputs', sa.Boolean(), nullable=False),
    sa.Column('capture_context', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Enforcement gates for control policy evaluation (Phase 3: Enforcement)'
    )
    op.create_index('idx_gate_active', 'enforcement_gates', ['is_active', 'gate_type'], unique=False)
    op.create_index('idx_gate_capability', 'enforcement_gates', ['capability_id', 'gate_type', 'is_active'], unique=False)
    op.create_index('idx_gate_workflow', 'enforcement_gates', ['workflow_id', 'gate_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_enforcement_gates_capability_id'), 'enforcement_gates', ['capability_id'], unique=False)
    op.create_index(op.f('ix_enforcement_gates_gate_key'), 'enforcement_gates', ['gate_key'], unique=True)
    op.create_index(op.f('ix_enforcement_gates_gate_type'), 'enforcement_gates', ['gate_type'], unique=False)
    op.create_index(op.f('ix_enforcement_gates_is_active'), 'enforcement_gates', ['is_active'], unique=False)
    op.create_index(op.f('ix_enforcement_gates_workflow_id'), 'enforcement_gates', ['workflow_id'], unique=False)
    op.create_table('gate_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('gate_key', sa.String(length=100), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.Enum('ALLOW', 'BLOCK', 'WARNING', 'HARD_STOP', 'DEGRADE', name='gateoutcome'), nullable=False),
    sa.Column('controls_evaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kill_switches_checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['enforcement_gates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Gate execution history for analytics and debugging (Phase 3: Enforcement)'
    )
    op.create_index('idx_gate_exec_actor', 'gate_executions', ['actor_id', 'executed_at'], unique=False)
    op.create_index('idx_gate_exec_gate_time', 'gate_executions', ['gate_id', 'executed_at'], unique=False)
    op.create_index('idx_gate_exec_outcome_time', 'gate_executions', ['outcome', 'executed_at'], unique=False)
    op.create_index('idx_gate_exec_request', 'gate_executions', ['request_id'], unique=False)
    op.create_index(op.f('ix_gate_executions_actor_id'), 'gate_executions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_gate_executions_executed_at'), 'gate_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_gate_executions_execution_id'), 'gate_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_gate_executions_gate_id'), 'gate_executions', ['gate_id'], unique=False)
    op.create_index(op.f('ix_gate_executions_gate_key'), 'gate_executions', ['gate_key'], unique=False)
    op.create_index(op.f('ix_gate_executions_outcome'), 'gate_executions', ['outcome'], unique=False)
    op.create_index(op.f('ix_gate_executions_request_id'), 'gate_executions', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_executions_request_id'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_outcome'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_gate_key'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_gate_id'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_execution_id'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_executed_at'), table_name='gate_executions')
    op.drop_index(op.f('ix_gate_executions_actor_id'), table_name='gate_executions')
    op.drop_index('idx_gate_exec_request', table_name='gate_executions')
    op.drop_index('idx_gate_exec_outcome_time', table_name='gate_executions')
    op.drop_index('idx_gate_exec_gate_time', table_name='gate_executions')
    op.drop_index('idx_gate_exec_actor', table_name='gate_executions')
    op.drop_table('gate_executions')
    op.drop_index(op.f('ix_enforcement_gates_workflow_id'), table_name='enforcement_gates')
    op.drop_index(op.f('ix_enforcement_gates_is_active'), table_name='enforcement_gates')
    op.drop_index(op.f('ix_enforcement_gates_gate_type'), table_name='enforcement_gates')
    op.drop_index(op.f('ix_enforcement_gates_gate_key'), table_name='enforcement_gates')
    op.drop_index(op.f('ix_enforcement_gates_capability_id'), table_name='enforcement_gates')
    op.drop_index('idx_gate_workflow', table_name='enforcement_gates')
    op.drop_index('idx_gate_capability', table_name='enforcement_gates')
    op.drop_index('idx_gate_active', table_name='enforcement_gates')
    op.drop_table('enforcement_gates')
    op.drop_index(op.f('ix_connectors_connector_key'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_capability_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_change_requests_workflow_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_risk_level'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_requested_by'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_control_policy_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_change_type'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_change_key'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_capability_id'), table_name='change_requests')
    op.drop_index('idx_change_workflow', table_name='change_requests')
    op.drop_index('idx_change_status_risk', table_name='change_requests')
    op.drop_index('idx_change_requested', table_name='change_requests')
    op.drop_index('idx_change_execution_window', table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_kill_switches_workflow_id'), table_name='kill_switches')
    op.drop_index(op.f('ix_kill_switches_switch_key'), table_name='kill_switches')
    op.drop_index(op.f('ix_kill_switches_incident_id'), table_name='kill_switches')
    op.drop_table('kill_switches')
    op.drop_index(op.f('ix_control_policies_workflow_id'), table_name='control_policies')
    op.drop_index(op.f('ix_control_policies_policy_key'), table_name='control_policies')
    op.drop_table('control_policies')
    op.drop_index(op.f('ix_capabilities_workflow_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_key'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_break_glass_workflow_id'), table_name='break_glass')
    op.drop_index(op.f('ix_break_glass_incident_id'), table_name='break_glass')
    op.drop_index(op.f('ix_break_glass_break_glass_key'), table_name='break_glass')
    op.drop_table('break_glass')
    op.drop_index(op.f('ix_workflows_workflow_key'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_tenants_tenant_key'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index('idx_audit_resource', table_name='audit_events')
    op.drop_index('idx_audit_outcome', table_name='audit_events')
    op.drop_index('idx_audit_event_type_time', table_name='audit_events')
    op.drop_index('idx_audit_actor_time', table_name='audit_events')
    op.drop_table('audit_events')
    # Drop PostgreSQL ENUM types (not auto-dropped by Alembic)
    sa.Enum(name='gateoutcome').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gatetype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='connectortype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='changestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='changerisklevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='changetype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='killswitchtrigger').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='killswitchmode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='approvaltype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='policyaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='breakglassstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='breakglassreason').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workflowstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risklevel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
